apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exemple-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exemple-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exemple-role
subjects: 
- kind: User
  name: example-user