apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        imagePullPolicy: IfNotPresent
        command: [ "redis-server" ]
        args: [ "--save 60 1", "--loglevel warning" ]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-state
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-state
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
