services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    image: olegon/fiap-soat-docker-challenge:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - db
