CREATE TABLE programming_languages(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);

INSERT INTO programming_languages ("name")
VALUES 
    ('Java'),
    ('Kotlin'),
    ('C#'),
    ('Rust'),
    ('C++'),
    ('JavaScript');

\d programming_languages;
